# Generated by Django 3.2 on 2021-08-07 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poligon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_points', models.PositiveIntegerField(blank=True, default=0)),
                ('distance', models.PositiveIntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_x', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14)),
                ('point_y', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14)),
                ('poligon_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mypoligon.poligon')),
            ],
        ),
    ]
